[package]
name = "cdr-encoding-size-derive"
version = "0.1.1"
edition = "2018"
authors = ["Juhana Helovuo <juhe@iki.fi>"]
repository = "https://github.com/jhelovuo/cdr-encoding"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

